/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface BAvatar {
        "href": string;
        "src": string;
        "username": string;
    }
    interface BLink {
        "href": string;
        "target": (
    | '_blank'
    | '_self'
    | '_parent'
    | '_top'
  );
        "upperCase": boolean;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLBAvatarElement extends Components.BAvatar, HTMLStencilElement {
    }
    var HTMLBAvatarElement: {
        prototype: HTMLBAvatarElement;
        new (): HTMLBAvatarElement;
    };
    interface HTMLBLinkElement extends Components.BLink, HTMLStencilElement {
    }
    var HTMLBLinkElement: {
        prototype: HTMLBLinkElement;
        new (): HTMLBLinkElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "b-avatar": HTMLBAvatarElement;
        "b-link": HTMLBLinkElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface BAvatar {
        "href": string;
        "src": string;
        "username": string;
    }
    interface BLink {
        "href": string;
        "target"?: (
    | '_blank'
    | '_self'
    | '_parent'
    | '_top'
  );
        "upperCase"?: boolean;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "b-avatar": BAvatar;
        "b-link": BLink;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "b-avatar": LocalJSX.BAvatar & JSXBase.HTMLAttributes<HTMLBAvatarElement>;
            "b-link": LocalJSX.BLink & JSXBase.HTMLAttributes<HTMLBLinkElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
